version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - PG_PROJECT_USER=${PGUSER}
      - PG_PROJECT_PASSWORD=${PGPASSWORD}
      - PG_PROJECT_DATABASE=${PGDATABASE}
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./superuser.sql:/sql/superuser.sql
    ports:
      - 5430:5432